[build]
  command = "echo 'No build step needed'"
  publish = "public"
  functions = "netlify/functions"
  environment = { NETLIFY_USE_XENIAL = "true" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200